//! Write a circuit — parts and the nets between their pins — as a SKiDL
//! script, the pipeline's circuit IR.
//!
//! Knows nothing about any board: what the parts are and why they are there is
//! decided upstream (by [`crate::synth`]). Pins are connected by the **name**
//! the symbol gives them wherever possible, through a `pins()` helper that
//! fails hard when a name is missing — SKiDL on its own only logs it.

use std::collections::BTreeMap;

/// Where a part's pins come from.
#[derive(Debug, Clone, PartialEq)]
pub enum SymbolSrc {
    /// An official KiCad symbol: `("Lib", "Name")`.
    Kicad(String, String),
    /// No KiCad symbol: `(number, name, io)` from the datasheet's pin table,
    /// `io` being its I/O column (`I`, `O`, `I/O`, `power`, `passive`).
    Inline(Vec<(String, String, String)>),
}

#[derive(Debug, Clone, PartialEq)]
pub struct EmitPart {
    pub reference: String,
    pub symbol: SymbolSrc,
    pub value: String,
    pub footprint: String,
    /// Extra netlist fields: `MPN`, `LCSC`, `Sim.Enable`, …
    pub fields: BTreeMap<String, String>,
}

/// One end of a connection.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum PinRef {
    /// Every pin of the part carrying this name (all five VDD pins).
    Name(String),
    /// The `k`th pin carrying this name, for a name the design must not join
    /// (each of an H7's VCAP pins gets its own capacitor).
    NameAt(String, usize),
    /// A pin by number — two-terminal passives, numbered 1 and 2.
    Num(u32),
}

/// A circuit ready to write.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Circuit {
    pub title: String,
    pub parts: Vec<EmitPart>,
    pub nets: BTreeMap<String, Vec<(String, PinRef)>>,
}

impl Circuit {
    pub fn connect(&mut self, net: &str, reference: &str, pin: PinRef) {
        self.nets
            .entry(net.to_string())
            .or_default()
            .push((reference.to_string(), pin));
    }

    /// The SKiDL script — a pure function of the circuit.
    pub fn to_skidl(&self) -> String {
        let var = |r: &str| r.to_lowercase().replace(['+', '-', '.'], "_");
        let mut body = String::new();
        for p in &self.parts {
            let v = var(&p.reference);
            match &p.symbol {
                SymbolSrc::Kicad(lib, name) => body.push_str(&format!(
                    "    {v} = Part({lib:?}, {name:?}, ref={r:?}, value={val:?}, footprint={f:?})\n",
                    r = p.reference,
                    val = p.value,
                    f = p.footprint
                )),
                SymbolSrc::Inline(pins) => {
                    let pins: Vec<String> = pins
                        .iter()
                        .map(|(n, name, io)| {
                            let func = match io.as_str() {
                                "I" => "INPUT",
                                "O" => "OUTPUT",
                                "I/O" => "BIDIR",
                                "power" => "PWRIN",
                                _ => "PASSIVE",
                            };
                            format!("Pin(num={n:?}, name={name:?}, func=Pin.types.{func})")
                        })
                        .collect();
                    body.push_str(&format!(
                        "    {v} = Part(tool=SKIDL, name={val:?}, ref={r:?}, value={val:?}, footprint={f:?},\n             pins=[{pins}])\n",
                        r = p.reference,
                        val = p.value,
                        f = p.footprint,
                        pins = pins.join(", ")
                    ));
                }
            }
            for (k, val) in &p.fields {
                body.push_str(&format!("    {v}.fields[{k:?}] = {val:?}\n"));
            }
            body.push_str(&format!("    parts.append({v})\n"));
        }
        body.push('\n');
        for (net, pins) in &self.nets {
            let refs: Vec<String> = pins
                .iter()
                .map(|(r, pin)| match pin {
                    PinRef::Name(n) => format!("pins({}, {n:?})", var(r)),
                    PinRef::NameAt(n, k) => format!("pins({}, {n:?})[{k}]", var(r)),
                    PinRef::Num(n) => format!("{}.p[{n}]", var(r)),
                })
                .collect();
            body.push_str(&format!("    Net({net:?}).connect({})\n", refs.join(", ")));
        }

        format!(
            r#"#!/usr/bin/env python3
"""{title}

Generated by legion-of-bom from a decided design spec: every part, pin
binding and value traces to a typed decision or a cited catalog fact.
Run standalone (needs KICAD9_SYMBOL_DIR); `lob run` sets it up.
"""

import argparse
import builtins
import sys

from skidl import ERC, SKIDL, Net, Part, Pin, generate_netlist


def pins(part, name):
    """Every pin of `part` named `name` -- and a hard failure if there is none,
    where SKiDL itself would only log it."""
    found = part.n[name]
    # A plain list: SKiDL's NetPinList indexes like a bus, not a sequence.
    found = list(found) if isinstance(found, list) else [found]
    if not found or found == [None]:
        raise SystemExit(f"{{part.ref}} has no pin named {{name!r}}")
    return found


def build():
    parts = []
{body}
    # Every pin the design does not use is an explicit no-connect.
    for part in parts:
        for p in part.pins:
            if not p.is_connected():
                p += builtins.NC
    return parts


def main():
    parser = argparse.ArgumentParser(description={title:?})
    parser.add_argument("--output", default="circuit.net", help="netlist output path")
    args = parser.parse_args()
    build()
    erc_ok = ERC()
    generate_netlist(file_=args.output)
    if erc_ok is False:
        sys.exit(1)


if __name__ == "__main__":
    main()
"#,
            title = self.title,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ic_pins_by_name_passives_by_number_fields_carried() {
        let mut c = Circuit {
            title: "t".into(),
            ..Circuit::default()
        };
        c.parts.push(EmitPart {
            reference: "U1".into(),
            symbol: SymbolSrc::Kicad("Audio".into(), "PCM5102A".into()),
            value: "PCM5102A".into(),
            footprint: "fp".into(),
            fields: [("LCSC".to_string(), "C107671".to_string())].into(),
        });
        c.connect("+3V3", "U1", PinRef::Name("AVDD".into()));
        c.connect("VCAP1", "U1", PinRef::NameAt("VCAP".into(), 0));
        c.connect("GND", "C1", PinRef::Num(2));
        let py = c.to_skidl();
        assert!(
            py.contains(r#"Net("+3V3").connect(pins(u1, "AVDD"))"#),
            "{py}"
        );
        assert!(py.contains(r#"pins(u1, "VCAP")[0]"#));
        assert!(py.contains("c1.p[2]"));
        assert!(py.contains(r#"u1.fields["LCSC"] = "C107671""#));
    }

    #[test]
    fn an_inline_part_carries_its_pin_types() {
        let mut c = Circuit::default();
        c.parts.push(EmitPart {
            reference: "U2".into(),
            symbol: SymbolSrc::Inline(vec![("6".into(), "SCKI".into(), "I".into())]),
            value: "PCM1808".into(),
            footprint: "fp".into(),
            fields: BTreeMap::new(),
        });
        assert!(c
            .to_skidl()
            .contains(r#"Pin(num="6", name="SCKI", func=Pin.types.INPUT)"#));
    }
}
